name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: 'Assemble JAR'
        run: |
        ./gradlew assemble


      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: ‘cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar